name = "cat"
color = "#c0caf5"
speed = 700

[moods]
idle = [''' /\_/\
( o.o )
 > ^ <''', ''' /\_/\
( o.o )
 > ^ <''', ''' /\_/\
( o.o )
 > ^ <''', ''' /\_/\
( -.- )
 > ^ <''']
happy = [''' /\_/\
( ^.^ )
 > ^ <''']
excited = [''' /\_/\
( O.O )
 > ^ <''', '''\/\_/\/
( *.* )
 > ^ <''']
love = [''' /\_/\
( ♥.♥ )
 > ^ <''', ''' /\♥/\
( ♥.♥ )
 > ^ <''']
sad = [''' /\_/\
( ;.; )
 > ^ <''']
surprised = [''' /\_/\
( O.O )
 > o <''']
sleepy = [''' /\_/\ z
( -.- )
 > ^ <''', ''' /\_/\ Z
( -.- )
 > ^ <''']
curious = [''' /\_/\
( o.O )
 > ^ <''', ''' /\_/\
( O.o )
 > ^ <''']
searching = [''' /\_/\
(o.o  )
 > ^ <''', ''' /\_/\
(  o.o)
 > ^ <''']
proud = [''' /\_/\
( ^.~ )
 > ^ <''']
dizzy = [''' /\_/\
( @.@ )
 > ^ <''']

[says]
petted = ["purr", "mrrp ♥", "*headbutts*"]
