//! Short, plain definitions for the site's kink list. The website has none, so these
//! ship with yap and never need the network.

const DEFINITIONS: &[(&str, &str)] = &[
    ("3+ Penetration", "Three or more penetrations at once."),
    ("Age Differences", "Adult partners with a notable gap in age."),
    ("Age Progression", "A character growing older, as a transformation."),
    ("Age Regression", "A character taking on a younger mindset or role, as in caregiver-style age play."),
    ("All the Way Through", "Penetration imagined passing from one end of the body to the other."),
    ("Anal Vore", "Vore where a character is drawn in through the anus."),
    ("Anal", "Anal sex and play."),
    ("Androgyny", "Characters who look or present as neither clearly masculine nor feminine."),
    ("Animal Transformation", "A character turning into an animal, or a more animal form."),
    ("Aphrodisiacs", "Substances that heighten arousal."),
    ("Ass to Mouth", "Oral contact straight after anal penetration."),
    ("Ass Worship", "Adoring, kissing and praising a partner's rear."),
    ("Auto-Fellatio", "Performing oral sex on oneself."),
    ("Barbed Cocks", "Penises with soft barbs or spines, as on felines."),
    ("Begging", "One partner pleading for touch, release or mercy."),
    ("Belly Fucking", "Penetration of a navel or belly opening; fantastical."),
    ("Bimbofication", "A character becoming curvier and more airheaded, often by transformation."),
    ("Birthing", "Giving birth, often after pregnancy or egg-laying play."),
    ("Biting", "Biting and nibbling during sex."),
    ("Blood", "Blood appearing in a scene."),
    ("Bloodplay", "Drawing, tasting or playing with blood as part of sex."),
    ("Body Swapping", "Characters exchanging bodies."),
    ("Body Writing", "Writing words or tallies on a partner's body."),
    ("Bondage", "Restraining a partner with rope, cuffs or similar."),
    ("Branding", "Marking a partner permanently, as with a brand or tattoo."),
    ("Breeding", "Sex framed around impregnating or being impregnated."),
    ("Bukkake", "Several partners ejaculating onto one person."),
    ("Caging", "Keeping a partner in a cage or enclosure."),
    ("Cervical Penetration", "Penetration past the cervix; fantastical."),
    ("Chastity", "Denying access to the genitals, often with a chastity device."),
    ("Choking", "Pressure on the throat, or play that simulates it."),
    ("Chubby", "Soft, plump or chubby characters."),
    ("Clit Play", "Focused attention on the clitoris."),
    ("CNC", "Consensual non-consent: roleplaying unwillingness within agreed limits."),
    ("Cock Vore", "Vore where a character is drawn in through the penis."),
    ("Condoms", "Using condoms, or making a feature of them."),
    ("Corruption", "An innocent character gradually drawn into lust or depravity."),
    ("Creampie", "Ejaculating inside a partner, with it leaking out afterwards."),
    ("Crossdressing", "Wearing clothes usually associated with another gender."),
    ("Crotch Sniffing", "Smelling a partner's crotch and scent."),
    ("Cum Bath", "Being soaked or bathed in semen."),
    ("Cum Enemas", "Filling the rectum with semen."),
    ("Cum", "Semen and ejaculation as a focus."),
    ("Cuntboys", "Male characters with a vagina."),
    ("Deepthroat", "Taking a penis deep into the throat."),
    ("Degradation", "Demeaning a partner with words or treatment."),
    ("Diapers", "Wearing or using diapers, often tied to age play."),
    ("Digestion", "Vore that goes on to the prey being digested."),
    ("Dirty Talking", "Explicit, crude talk during sex."),
    ("Docking", "One penis's foreskin drawn over another's."),
    ("Double Penetration", "Two penetrations at once."),
    ("Drug / Alcohol Use", "Characters under the influence during a scene."),
    ("Ear Play", "Touching, licking or nibbling ears."),
    ("Electric Toys", "Toys that give mild electric stimulation (e-stim)."),
    ("Enemas", "Flushing the rectum with liquid."),
    ("Excessive Cum", "Unrealistically large amounts of semen."),
    ("Exhibitionism", "Enjoying being seen while exposed or having sex."),
    ("Exotic Cocks", "Non-human penis shapes: tapered, knotted, ridged, prehensile and so on."),
    ("Face Fucking", "Thrusting into a partner's mouth while they stay passive."),
    ("Face Sitting", "Sitting on a partner's face."),
    ("Farting", "Flatulence as a kink."),
    ("Felching", "Sucking semen out of a partner after sex."),
    ("Fellatio", "Oral sex on a penis."),
    ("Femboys", "Feminine-presenting male characters."),
    ("Femininity", "Emphasis on feminine looks and behaviour."),
    ("Feminization", "Making a character more feminine by dress, behaviour or transformation."),
    ("Feral", "Characters with four-legged animal bodies rather than anthro ones."),
    ("Fisting", "Inserting a whole hand."),
    ("Flexibility", "Very flexible bodies and positions."),
    ("Food Play", "Using food on or with bodies during sex."),
    ("Foot Play", "Feet as a focus: licking, massage, footjobs."),
    ("Foreplay", "The build-up before sex: kissing, touching, teasing."),
    ("Foreskin Worship", "Attention on, and admiration of, the foreskin."),
    ("Frotting", "Rubbing bodies or genitals together without penetration."),
    ("Gags", "Gagging a partner's mouth."),
    ("Gangbangs", "Several partners on one person, together or in turn."),
    ("Gender Transformation", "A character changing sex."),
    ("Glory Hole", "Sex through a hole in a wall, partners unseen."),
    ("Group Sex", "More than two participants."),
    ("Growth", "A character or body part growing larger."),
    ("Hair Pulling", "Pulling hair or fur during sex."),
    ("Hand Cuffs", "Restraint with handcuffs."),
    ("Handjob / Fingering", "Stimulating the genitals by hand."),
    ("Hard Vore", "Graphic vore involving chewing or injury."),
    ("Horns", "Horned characters, or horns used as handles."),
    ("Hotdogging", "Sliding a penis between the buttocks without penetration."),
    ("Humiliation", "Embarrassing or shaming a partner for arousal."),
    ("Hyper Asses", "Enormously oversized rears."),
    ("Hyper Balls", "Enormously oversized testicles."),
    ("Hyper Breasts", "Enormously oversized breasts."),
    ("Hyper Cocks", "Enormously oversized penises."),
    ("Hyper Fat", "Extremely large, heavy bodies."),
    ("Hyper Muscle", "Extremely exaggerated musculature."),
    ("Hyper Vaginas", "Enormously oversized vulvas."),
    ("Hyper", "Body parts exaggerated far beyond realistic size."),
    ("Hyper-Voluptuous", "Extremely exaggerated curves all over."),
    ("Ice", "Ice and cold used for sensation play."),
    ("In Heat", "A character in estrus, driven by instinctive arousal."),
    ("Incest", "Sex between fictional family members."),
    ("Inflation", "A belly or body swelling with air, liquid or cum."),
    ("Kissing", "Kissing, from gentle to deep."),
    ("Knotted Cocks", "Canine-style penises with a knot at the base."),
    ("Knotting", "Tying with a knot so partners stay locked together."),
    ("Lactation", "Producing or drinking milk."),
    ("Leash & Collar", "Wearing a collar and being led on a leash."),
    ("Licking", "Licking a partner, anywhere."),
    ("Living Insertions", "Inserting a small living creature; fantastical."),
    ("Macrophilia", "Attraction to giants and giantesses."),
    ("Magic Users", "Characters who use magic in the scene."),
    ("Male Pregnancy", "Male characters becoming pregnant."),
    ("Masculinity", "Emphasis on masculine looks and behaviour."),
    ("Masturbation", "Self-pleasure, alone or watched."),
    ("Messy", "Sex that gets sticky, sloppy or wet."),
    ("Microphilia", "Attraction to tiny characters."),
    ("Mind Control", "Hypnosis or other control over a character's mind."),
    ("Multiple Orgasms", "Climaxing several times."),
    ("Musk", "Strong body scent as an attraction."),
    ("Natural Musk", "Unwashed, natural body odour as an attraction."),
    ("Navel Play", "Attention on the belly button."),
    ("Nipple Penetration", "Penetration of a nipple; fantastical."),
    ("Nipple Piercings", "Pierced nipples."),
    ("Nursing", "Suckling at a breast."),
    ("Objectification", "Treating a partner as an object."),
    ("Objectophilia", "Attraction to inanimate objects."),
    ("Oral Fixation", "A strong focus on the mouth: sucking, licking, kissing."),
    ("Orgasm Control", "One partner deciding when, or whether, the other climaxes."),
    ("Oviposition", "Laying eggs inside a partner."),
    ("Pain", "Pain as a source of pleasure."),
    ("Paw Play", "Paws as a focus: pads, pawjobs, massage."),
    ("Pegging", "A woman penetrating a man with a strap-on."),
    ("Pet / Master", "One partner as an owned pet, the other as their owner."),
    ("Piercings", "Body or genital piercings."),
    ("Powerbottoming", "The receiving partner taking charge."),
    ("Pregnancy", "Pregnancy and pregnant bodies."),
    ("Prolapse", "Rectal or vaginal prolapse; usually fantastical."),
    ("Prostate Play", "Stimulating the prostate."),
    ("Prostitution", "Sex exchanged for money."),
    ("Public Humiliation", "Being embarrassed in front of others."),
    ("Queefing", "Air released from the vagina."),
    ("Rimming", "Oral stimulation of the anus."),
    ("Rubber / Elastic / Latex", "Latex or rubber clothing, or stretchy, rubbery bodies."),
    ("Saliva", "Drool and spit as a focus."),
    ("Scat", "Feces as a kink."),
    ("Scissoring", "Rubbing vulvas together with legs interlocked."),
    ("Scratching", "Scratching with claws or nails."),
    ("Sex Toys", "Dildos, vibrators, plugs and other toys."),
    ("Sexual Frustration", "Being kept aroused but unsatisfied."),
    ("Shaving", "Shaving fur or hair, especially in intimate places."),
    ("Sheath Play", "Attention on the sheath of an animal-style penis."),
    ("Shrinking", "A character getting smaller."),
    ("Size Difference", "Partners of very different sizes."),
    ("Slapping", "Slapping, on the face or elsewhere."),
    ("Slime", "Slime creatures, or goo covering bodies."),
    ("Sloppy Seconds", "Sex with someone straight after another partner."),
    ("Small Breasts", "Characters with small breasts."),
    ("Smoking", "Smoking as a kink."),
    ("Snowballing", "Passing semen from mouth to mouth."),
    ("Soft Vore", "Swallowing a creature whole without harm."),
    ("Somnophilia", "Arousal from sex with a sleeping partner."),
    ("Sounding", "Inserting smooth rods into the urethra."),
    ("Spanking", "Spanking the rear."),
    ("Squirting", "Female ejaculation."),
    ("Stomach Bulging", "A belly visibly bulging from what's inside it."),
    ("Strap-ons", "A harnessed dildo worn to penetrate a partner."),
    ("Strip Tease", "Undressing slowly for a watching partner."),
    ("Stuckage", "A character stuck in a wall, hole or other tight spot."),
    ("Swallowing", "Swallowing semen."),
    ("Sweat", "Sweat and sweaty bodies."),
    ("Tail Pulling", "Pulling or tugging a tail."),
    ("Tail Sex", "Using a tail to stimulate or penetrate."),
    ("Tailsex", "Using a tail to stimulate or penetrate (same as Tail Sex)."),
    ("Teasing", "Drawing out arousal and making a partner wait."),
    ("Teeth Play", "Teeth grazing and nipping, gently."),
    ("Tentacles", "Tentacles, whether on creatures or as appendages."),
    ("Throat Penetration", "Penetration deep into the throat."),
    ("Tickling", "Tickling a partner."),
    ("Titfucking", "A penis thrust between breasts."),
    ("Tomboys", "Boyish female characters."),
    ("Transformation", "Any change of body or form: species, size, gender."),
    ("Twinks", "Slim, smooth-bodied men."),
    ("Twins", "Twin characters, together or with a partner."),
    ("Udders", "Characters with udders."),
    ("Unusual Semen", "Semen of an odd colour, taste or substance."),
    ("Urethra Play", "Stimulating the urethra."),
    ("Vanilla Sex", "Conventional sex without kinks."),
    ("Virgin", "A character's first time."),
    ("Vorarephilia", "Vore in general: attraction to eating, or being eaten, alive."),
    ("Voyeurism", "Enjoying watching others."),
    ("Watersports", "Urine play."),
    ("Wax Play", "Dripping warm wax on skin."),
    ("Whipping", "Whipping or flogging."),
];

/// A one-line definition of a kink from the site's list.
pub fn define(kink: &str) -> Option<&'static str> {
    DEFINITIONS.iter().find(|(k, _)| *k == kink).map(|(_, d)| *d)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::KINKS;

    #[test]
    fn every_kink_has_exactly_one_definition() {
        for kink in KINKS {
            assert!(define(kink).is_some(), "no definition for {kink}");
        }
        assert_eq!(DEFINITIONS.len(), KINKS.len(), "definitions for kinks the site doesn't have");
    }
}
